name: WIF Demo ## For demo purpose without any service account #runner sample demo purpose asdfkjkajf

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP using WIF
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/102063365001/locations/global/workloadIdentityPools/github/providers/ github-provider"
        service_account: "wif-binding-gcp-githubactions@project-99191d06-06e7-4c9c-be1.iam.gserviceaccount.com"

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify Access
      run: |
        gcloud auth list
        gcloud projects list
