name: WIF Demo

on:
  push:

jobs:
  demo:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Authenticate to GCP using WIF
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/83814747678/locations/global/workloadIdentityPools/github-actions-pool/providers/github-provider"
        service_account: "wihtout-sa@project-d4fa532f-546b-4bdb-921.iam.gserviceaccount.com"

    - name: Setup gcloud
      uses: google-github-actions/setup-gcloud@v2

    - name: Verify Access
      run: |
        gcloud auth list
        gcloud projects list
